name: RK-Core
author: T4TU_
version: 2
main: me.t4tu.rkcore.Core
depend: [ProtocolLib, LangUtils]
commands:
  reconnect:
  updateplayerdata:
  playerlookup:
  kickall:
  huolto:
  xstop:
  autorestart:
  config:
  sql:
  list:
  who:
  pelaajat:
  alert:
  send:
  chat:
  perm:
  group:
  history:
  halttime:
  give:
  effect:
  sudo:
  sudochat:
  setnews:
  vanhentuneetsakot:
  clearfire:
  debug:
  ping:
  lag:
  etsi:
  find:
  search:
  pelaaja:
  profiili:
  player:
  profile:
  p:
  help:
  apua:
  ?:
  säännöt:
  rules:
  s:
  sa:
  a:
  helpop:
  henkilökunta:
  staff:
  viesti:
  msg:
  tell:
  w:
  t:
  m:
  vastaa:
  r:
  posti:
  mail:
  afk:
  uutiset:
  news:
  motd:
  tilaviesti:
  status:
  kompassi:
  lähellä:
  near:
  spawn:
  hub:
  lobby:
  asetaspawn:
  setspawn:
  koti:
  home:
  asetakoti:
  sethome:
  poistakoti:
  delhome:
  matkusta:
  warp:
  setwarp:
  delwarp:
  swarp:
  setswarp:
  delswarp:
  spy:
  comspy:
  vanish:
  poof:
  god:
  fly:
  gamemode:
  gm:
  heal:
  feed:
  back:
  top:
  clear:
  ci:
  invsee:
  enderchest:
  echest:
  tp:
  tpo:
  tphere:
  tpohere:
  tppos:
  noafk:
  nick:
  fix:
  pt:
  thor:
  entity:
  mob:
  killall:
  xp:
  xpl:
  portti:
  maailma:
  world:
  holo:
  tutorial:
  rankaise:
  h:
  huomautus:
  note:
  sakko:
  sakot:
  tiketti:
  grief:
  ticket:
  tiketit:
  griefs:
  tickets:
  kaveri:
  kaverit:
  k:
  friend:
  friends:
  f:
  kc:
  gc:
  kilta:
  killat:
  guild:
  guilds:
  g:
  asetukset:
  settings:
  options:
  kick:
  mute:
  tempmute:
  unmute:
  jail:
  tempjail:
  unjail:
  ban:
  tempban:
  unban:
  ipban:
  ipunban:
  showlog:
  setjail: