name: RK-Core
author: T4TU_
version: 2
main: me.t4tu.rkcore.Core
depend: [LangUtils]
api-version: 1.13
commands:
    reconnect:
    setupmysql:
    updateplayerdata:
    playerlookup:
    kickall:
    huolto:
    xstop:
    autorestart:
    config:
    sql:
    statistics:
    list:
    who:
    pelaajat:
    alert:
    autobroadcast:
    send:
    chat:
    perm:
    group:
    history:
    halttime:
    give:
    effect:
    sudo:
    sudochat:
    setnews:
    vanhentuneetsakot:
    debug:
    ping:
    lag:
    etsi:
    find:
    search:
    pelaaja:
    profiili:
    player:
    profile:
    p:
    tilastot:
    stats:
    help:
    apua:
    ?:
    säännöt:
    rules:
    discord:
    bugi:
    bug:
    s:
    sa:
    a:
    helpop:
    ar:
    henkilökunta:
    staff:
    viesti:
    msg:
    tell:
    v:
    t:
    m:
    vastaa:
    r:
    posti:
    mail:
    afk:
    uutiset:
    news:
    motd:
    rainbow:
    tilaviesti:
    status:
    kompassi:
    kalenteri:
    päivämäärä:
    juhlapäivä:
    juhlapäivät:
    lähellä:
    near:
    sijainti:
    getpos:
    spawn:
    hub:
    lobby:
    asetaspawn:
    setspawn:
    setstartpoint:
    koti:
    home:
    asetakoti:
    sethome:
    nimeäkoti:
    namehome:
    poistakoti:
    delhome:
    matkusta:
    warp:
    setwarp:
    delwarp:
    swarp:
    setswarp:
    delswarp:
    spy:
    comspy:
    vanish:
    poof:
    god:
    fly:
    gamemode:
    gm:
    heal:
    feed:
    back:
    top:
    clear:
    ci:
    invsee:
    enderchest:
    echest:
    swapinventories:
    evokkimoodi:
    endinaattori:
    tp:
    tpo:
    tphere:
    tpohere:
    tppos:
    noafk:
    lempinimi:
    nick:
    fix:
    name:
    lore:
    setamount:
    pt:
    lightfix:
    thor:
    entity:
    mob:
    killall:
    xp:
    xpl:
    portti:
    tykki:
    kallot:
    komentokuutio:
    command-block:
    maailma:
    world:
    talli:
    stable:
    holo:
    armorstand:
    stand:
    vnpc:
    tutorial:
    tardis:
    musiikkikauppa:
    pvpstats:
    matka:
    rankaise:
    h:
    huomautus:
    note:
    sakko:
    sakot:
    tiketti:
    grief:
    ticket:
    tiketit:
    griefs:
    tickets:
    kaveri:
    kaverit:
    k:
    friend:
    friends:
    f:
    kc:
    gc:
    kilta:
    killat:
    guild:
    guilds:
    g:
    pc:
    party:
    asetukset:
    settings:
    options:
    kick:
    mute:
    tempmute:
    unmute:
    jail:
    tempjail:
    unjail:
    ban:
    tempban:
    unban:
    ipban:
    ipunban:
    showlog:
    setjail: